catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed')
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include ('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/')),
    path('accounts/', include('django.contrib.auth.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date
import uuid


class Genre(models.Model):
    """Model representing a genre book """
    name =  models.CharField(max_length=200, help_text='Enter book genre(e.g. Science Fiction)')

    def __str__(self):
        """String representing the Model object"""
        return self.name

class Language(models.Model):
    """Model representing a Language (English, French, etc"""
    name = models.CharField(max_length=100, help_text='Enter the books natural language')

    def __str__(self):
        """Printing the model representation"""
        return self.name

class Book(models.Model):
    """Model representing a book but not a very specific book"""

    title = models.CharField(max_length=200)
    # Foreign key used because book can only have one author, but authors can have multiple books"""
    # Author as sa string rather than an object because it has not been declared in the file yet
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)

    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, unique=True)

    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    genre = models.ManyToManyField(Genre, help_text='Select genre for this book')

    def __str__(self):
        """String representing the model Model object"""
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book"""
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        """Create a string for Genre. This is required to display genre in Admin"""
        return ', '.join(genre.name for genre in self.genre.all()[:3])
    display_genre.short_description = 'Genre'

class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this paritcular book across the whole library ')
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id}({self.book.title})'

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

class Author(models.Model):
    """Model representing the author"""
    first_name = models.CharField(max_length=100)
    last_name  = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance"""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """string representing the model object"""
        return f'{self.first_name}, {self.last_name}'

catalog/views.py
from django.shortcuts import render
from catalog.models import Book, Author, BookInstance, Genre
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

class BookListView(generic.ListView):
    model = Book
    paginate_by = 2

class BookDetailView(generic.DetailView):
    model = Book

class AuthorListView(generic.ListView):
    model = Author

class AuthorDetailView(generic.DetailView):
    model = Author

class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """Generic class-based view listing books on loan to current user"""
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 2

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

def index(request):
    """View function for home page of site """

    #Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    #Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()

    # The 'all()' is implied by default
    num_authors = Author.objects.count()

    #Number of visits to this view, as counted in the session variable
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1

    num_genre = Genre.objects.all().count()
    book_contain = Book.objects.filter(title__contains='Fall').count()

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_genre': num_genre,
        'book_contain': book_contain,
        'num_visits': num_visits,
    }

    # Render the HTML template index.html with the data in teh context variable
    return render(request, 'index.html', context=context)

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>Local Library</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            {% block sidebar %}
                <ul class="sidebar-nav">
                    <li><a href="{% url 'index' %}">Home</a></li>
                    <li><a href="{% url 'books' %}">All Books</a></li>
                    <li><a href="{% url 'authors' %}">All authors</a></li>
                </ul>
            {% endblock %}
        </div>
        <div class="col-sm-10 ">
            {% block content %}{% endblock %}
            {% block pagination %}
                {% if is_paginated %}
                    <div class="pagination">
                        <span class="page-links">
                        {% if page_object.has_previous %}
                            <a href="{{ request.path }}?page={{ page_object.previous_page_number }}"> previous</a>
                        {% endif %}
                            <span class="page-current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>
                            {% if page_obj.has_next %}
                                <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                            {% endif %}
                    </span>
                    </div>
                {% endif %}
                <ul class="sidebar-nav">
                    {% if user.is_authenticated %}
                    <li>User : {{ user.get_username }}</li>
                    <li><a href="{% url 'my-borrowed' %}">My Borrowed</a></li>
                    <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'login' %}?next={{ request.path }}"></a></li>
                    {% endif %}
                </ul>
            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Author {{ author }}</h1>
    <p>{{ author.date_of_birth }} - {% if author.date_of_death %}{{ author.date_of_death }}{% endif %}</p>

    <div style="margin-left:20px;margin-top:20px">
        <h4>Books</h4>
    <dl>
        {% for book in author.book_set.all %}
            <dt><a href="{% url 'book-detail' book.pk %}">{{ book }}</a>({{ book.bookinstance_set.all.count }})</dt>
            <dd>{{ book.summary }}</dd>
        {% endfor %}
    </dl>
    </div>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Author List</h1>
    {% if author_list %}
        <ul>
            {%  for author in author_list %}
                <li>
                    <a href="{{ author.get_absolute_url }}">{{ author.first_name}} {{ author.last_name }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no authors in the library.</p>
    {%  endif %}
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Book List</h1>
    {% if book_list %}
        <ul>
        {%  for book in book_list %}
            <li>
            <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{ book.author }})
            </li>
        {% endfor %}
        </ul>
        {% else %}
            <p>There are no books in the library.</p>
    {%  endif %}
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
        <ul>
            {% for bookinst in bookinstance_list %}
                <li class="{% if bookinst.is_overdue %}text_danger{% endif %}">
                    <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a>({{ bookinst.due_back }})
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>The are no books borrowed.</p>
    {% endif %}
{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block title  %} <title> New Title</title>{% endblock %}

{% block content %}
  <h1>Local Library Home</h1>
  <p>Welcome to LocalLibrary, a website developed by <em>Mozilla Developer Network</em>!</p>
  <h2>Dynamic content</h2>
  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
      <li><strong>Number of Genre:</strong> {{ num_genre }}</li>
      <li><strong>Books with "Fall":</strong> {{ book_contain }}</li>
  </ul>
   <p>You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}.</p>

{% endblock %}